name: Execute and Publish Selected Notebooks

on:
  schedule:
    - cron: "0 */10 * * *"  # runs workflow every 10 minutes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  execute-and-publish-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install nbconvert notebook pandas numpy seaborn

      - name: Monitor Notebooks for Changes
        run: |
          bash ./setup_files/workflows/monitor_notebooks.sh

      - name: Execute Modified Notebooks
        if: success()
        run: |
          if [ -s modified_notebooks.txt ]; then
            for notebook in $(cat modified_notebooks.txt); do
              jupyter nbconvert --to notebook --execute "$notebook" --inplace
            done
          else
            echo "No modified notebooks to execute."
          fi
          
      - name: Publish Notebooks
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -s modified_notebooks.txt ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add ./*.ipynb
            git commit -m "Update executed notebooks"
            git push origin main
          else
            echo "No modified notebooks to publish."
          fi
