name: Execute and Publish Notebooks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute-and-publish-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install nbconvert notebook

      - name: Execute Notebooks
        continue-on-error: true  # Allows the workflow to continue even if one notebook fails
        run: |
          dir_path="published_notebooks/"  # Set the directory path where notebooks are located
          for notebook in $(find "$dir_path" -name "*.ipynb"); do
            echo "Executing $notebook..."
            jupyter nbconvert --to notebook --execute "$notebook" --inplace || echo "$notebook failed to execute"
          done

      - name: Publish Notebooks
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ./*.ipynb
          git commit -m "Update executed notebooks" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
